version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./www/:/var/www/
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "80:80"
    container_name: nginx_simple_php

  php:
    image: php:8.1-fpm-alpine
    volumes:
      - ./www/:/var/www
