version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./www/:/var/www/
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    container_name: nginx_simple

  php:
    image: php:8.1.1-fpm
    volumes:
      - ./www/:/var/www